# Generated by Django 6.0.2 on 2026-02-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('blocked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, max_length=120)),
                ('error_type', models.CharField(db_index=True, max_length=120)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, default='')),
                ('related_file', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FileProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, max_length=120)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='processing', max_length=16)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deletion_timestamp', models.DateTimeField(blank=True, null=True)),
                ('auto_delete', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IPUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('total_files_uploaded', models.PositiveIntegerField(default=0)),
                ('last_request', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('requests_today', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-total_requests'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('ram_usage', models.FloatField(default=0.0)),
                ('disk_usage', models.FloatField(default=0.0)),
                ('active_jobs', models.PositiveIntegerField(default=0)),
                ('queue_length', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ToolUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, max_length=120)),
                ('tool_category', models.CharField(db_index=True, max_length=64)),
                ('operation_count', models.PositiveIntegerField(default=1)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('processing_time_ms', models.PositiveIntegerField(default=0)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('conversion_from', models.CharField(blank=True, default='', max_length=32)),
                ('conversion_to', models.CharField(blank=True, default='', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
